[workspace]
members = [
    "gb_disas",
    "soc"
]

[package]
name = "rusty_boy"
version = "1.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
gl = "0.12.0"
glutin = "0.21.0"
bincode = "1.1.4"
structopt = {version = "0.2.18", default-features = false}
# Workspace dependencies.
soc = { path = "soc" }

# Uncomment for incremental release settings.
[profile.release]
#overflow-checks = true
#debug-assertions = true
incremental = true

# Uncomment for fully optimized release settings.
# [profile.release]
# codegen-units = 1
# lto = "fat"
# debug = true

# I use cargo test --release quite a bit.
[profile.bench]
overflow-checks = true
debug-assertions = true
incremental = true
