[workspace]
members = [
    "gb_disas",
    "soc"
]

[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
gl = "0.12.0"
glutin = "0.21.0"
serde_json = "1.0.39"
structopt = "0.2.15"
# Workspace dependencies.
soc = { path = "soc" }


[profile.release]
codegen-units = 16
overflow-checks = true
debug-assertions = true
incremental = true

# I use cargo test --release quite a bit.
[profile.bench]
debug-assertions = true
incremental = true
overflow-checks = true
codegen-units = 16

[profile.dev]
codegen-units = 16