[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
gl = "0.11.0"
glutin = "0.19.0"
bitfield = "0.13.1"
num-derive = "0.2.4"
num-traits = "0.2.6"

[dev-dependencies]
backtrace = "*"
