[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
gl = "0.12.0"
glutin = "0.20.0"
bitfield = "0.13.1"
num-derive = "0.2.4"
num-traits = "0.2.6"
csv = "1.0.7"
regex = "1.1.6"
lazy_static = "1.3.0"
gb_disas = { path = "gb_disas" }

[dev-dependencies]
backtrace = "0.3.15"

[profile.release]
debug = true