[workspace]
members = [
    "gb_disas",
    "soc"
]

[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
gl = "0.12.0"
glutin = "0.21.0"
# Workspace dependencies.
gb_disas = { path = "gb_disas" }
soc = { path = "soc" }


[profile.release]
overflow-checks = true
debug-assertions = true
lto = "fat"
incremental = true

# I use cargo test --release quite a bit.
[profile.bench]
debug-assertions = true
incremental = true
overflow-checks = true
lto = "thin"
codegen-units = 16

[profile.dev]
codegen-units = 16