[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
arrayvec = "0.4.10"
bitflags = "1.0.5"
fern = "0.5.8"
more-asserts = "0.2.1"
gl = "0.12.0"
glutin = "0.20.0"
bitfield = "0.13.1"
log = "0.4.6"
num-derive = "0.2.5"
num-traits = "0.2.6"
shrinkwraprs = "*"
csv = "1.0.7"
regex = "1.1.6"
lazy_static = "1.3.0"
gb_disas = { path = "gb_disas" }

[dev-dependencies]
backtrace = "0.3.15"
bmp = "*"

[profile.release]
debug = true
debug-assertions = true

[features]
log-timer = []