[workspace]
members = [
    "gb_disas",
    "soc"
]

[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
gl = "0.12.0"
glutin = "0.20.0"
# Workspace dependencies.
gb_disas = { path = "gb_disas" }
soc = { path = "soc" }

[profile.release]
debug = true
debug-assertions = true

[profile.dev]
codegen-units = 64