[workspace]
members = [
    "gb_disas",
    "soc"
]

[package]
name = "rusty_boy"
version = "1.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
gl = "0.12.0"
glutin = "0.21.0"
serde_json = "1.0.39"
structopt = "0.2.16"
# Workspace dependencies.
soc = { path = "soc" }


# Uncomment for incremental release settings.
# [profile.release]
# overflow-checks = true
# debug-assertions = true
# incremental = true

# Uncomment for fully optimized release settings.
# Make sure to build with RUSTFLAGS="-Ctarget-cpu=native" for slightly better performance.
[profile.release]
codegen-units = 1
lto = "fat"

# I use cargo test --release quite a bit.
[profile.bench]
overflow-checks = true
debug-assertions = true
incremental = true
# codegen-units = 1
# lto = "fat"

[profile.dev]
codegen-units = 16