[package]
name = "rusty_boy"
version = "0.1.0"
authors = ["Ramy"]

[dependencies]
glium = { git = "https://github.com/tomaka/glium.git" }
image = { git = "https://github.com/PistonDevelopers/image.git" }