edition = "2018"
version = "two"
unstable_features = true

max_width = 100
tab_spaces = 4

wrap_comments = true
comment_width = 100
format_strings = true

report_todo = "Always"
report_fixme = "Always"

fn_single_line = true