[package]
name = "soc"
version = "0.6.0"
authors = ["Ramy"]
edition = "2018"

[features]
default = ["audio"]
# Audio support. Disable this feature if you are having any audio problems (crashes, etc.).
audio = ["sample", "libsamplerate", "libsoundio-sys", "simple-error", "ringbuf"]
disas = ["gb_disas"]
# Enable for strict asserts that check for conditions that, while valid, are considered "bad" (e.g.
# writing to RAM when RAM is disabled, etc..).
strict_assert = []
# Use to log unit tests to a format that is shared with FPGA test environment.
serialize_tests = []

[dependencies]
arraydeque = "0.4.5"
arrayvec = {version = "0.4.11", features = ["serde-1"]}
bitflags = "1.1.0"
bitfield = "0.13.2"
csv = "1.1.1"
fern = "0.5.8"
lazy_static = "1.3.0"
log = {version = "0.4.7", features = ["max_level_trace", "release_max_level_trace"]}
more-asserts = "0.2.1"
num-derive = "0.2.5"
serde = {version = "1.0.94", features = ["derive", "rc"]}
serde_bytes = "0.11.1"
spin = "0.5.0"
typetag = "0.1.3"

gb_disas = { path = "../gb_disas", optional = true}

# Audio dependencies.
sample = { version = "0.10.0", optional = true }
libsamplerate = {version = "0.1.0", optional = true }
libsoundio-sys = { path = "../../soundio-rs/libsoundio-sys", optional = true }
simple-error = { version = "0.2.1", optional = true }
ringbuf = { version = "0.1.4", optional = true }

[dev-dependencies]
backtrace = "0.3.33"
bmp = "0.4.0"

[dependencies.num-traits]
version = "0.2.8"
default-features = false