[package]
name = "soc"
version = "0.5.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
arrayvec = "0.4.10"
bitflags = "1.0.4"
bitfield = "0.13.1"
csv = "1.0.7"
fern = "0.5.8"
lazy_static = "1.3.0"
log = "0.4.6"
more-asserts = "0.2.1"
num-derive = "0.2.5"
num-traits = "0.2.6"
regex = "1.1.6"

jemallocator = "0.3.0"

gb_disas = { path = "../gb_disas" }

[dev-dependencies]
backtrace = "0.3.15"
bmp = "0.4.0"

[features]
log-timer = []