[package]
name = "soc"
version = "0.5.0"
authors = ["Ramy"]
edition = "2018"

[dependencies]
arrayvec = {version = "0.4.10", features = ["serde-1"]}
bitflags = "1.0.4"
bitfield = "0.13.1"
csv = "1.0.7"
fern = "0.5.8"
lazy_static = "1.3.0"
log = "0.4.6"
more-asserts = "0.2.1"
num-derive = "0.2.5"
num-traits = "0.2.8"
regex = "1.1.6"
serde = {version = "1.0.91", features = ["derive", "rc"]}

jemallocator = "0.3.0"

gb_disas = { path = "../gb_disas" }

[dev-dependencies]
backtrace = "0.3.26"
bmp = "0.4.0"
itertools = "0.8.0"
threadpool = "1.7.1"

[features]
log-timer = []