name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Run tests (debug)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --workspace

      - name: Run tests (release)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

      - name: Build wasm32 target
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p soc --target wasm32-unknown-unknown
  
