name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests (debug)
      run: cargo test --verbose --workspace
    - name: Run tests (release)
      run: cargo test --release --verbose --workspace
